from hpolib.container.client.synthetic_functions.branin import Branin
from hpolib.container.client.synthetic_functions.hartmann3 import Hartmann3
from hpolib.container.client.synthetic_functions.hartmann6 import Hartmann6
from hpolib.container.client.synthetic_functions.camelback import Camelback
from hpolib.container.client.synthetic_functions.levy import Levy1D
from hpolib.container.client.synthetic_functions.bohachevsky import Bohachevsky
from hpolib.container.client.synthetic_functions.sin_one import SinOne
from hpolib.container.client.synthetic_functions.sin_two import SinTwo
from hpolib.container.client.synthetic_functions.goldstein_price import GoldsteinPrice
from hpolib.container.client.synthetic_functions.forrester import Forrester
